
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dal
{

using System;
    using System.Collections.Generic;
    
public partial class BankCardInfo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BankCardInfo()
    {

        this.UserInfo = new HashSet<UserInfo>();

    }


    public long BankCardInfoID { get; set; }

    public int BankID { get; set; }

    public string CardNumber { get; set; }

    public int CVV { get; set; }

    public System.DateTime ExtendDate { get; set; }



    public virtual Bank Bank { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserInfo> UserInfo { get; set; }

}

}
